---
title: "Income Tax Data Cleaning Project"
author: ""
---


Digital Platforms & Data Division (OCIO, CITZ) R code to reformat aggregated annual t1 tax data tables from Statistics Canada, provided by BCStats (JEDC).

The data comes in .xls format and are housed in the folder named `data-raw`.

In this project, the .xls files are tidied and merged into one csv sheet per table merging all years using R. 

The bcgov GitHub repository for this project can found here: https://github.com/bcgov/statscan-taxdata-tidying

The Technical Reference Guide for the Annual Income Estimates for Census Families, Individuals and Seniors is available on the Statistics Canada website:
[T1 Family File, Final Estimates, 2016](
https://www150.statcan.gc.ca/n1/pub/72-212-x/72-212-x2018001-eng.htm). For information about this product or the wide range of services and data available from Statistics Canada, visit their [website](www.statcan.gc.ca).
For further questions, the Statistics Canada email is <STATCAN.infostats-infostats.STATCAN@canada.ca>. 

This data (from Statistics Canada) includes information copied with permission from Canada Post Corporation. Information about Statistics Canada Open Licence can be found here: https://www.statcan.gc.ca/eng/reference/licence 

### Data Tables for Individuals & Families

Currently, the data includes income estimates for individuals aggregated for various geographical areas in B.C. ranging from years 2000 up to 2015. Income estimates for families range from years 2004 up to 2016. Each table is an aggregation of all years for that table.


### Data Tidying

The .xls data format contains empty cells, duplicate column names, table names in each sheet, nested tables, source declaration at end, etc. The individuals, individuals table 13, and families have various different formats and require unique clean-up. The scripts are designed to preserve data integrity and work automatically in order to clean the tables in batches.
